---
- hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

    - block:
      - name: Create temporary directory for downloading raw casks
        ansible.builtin.tempfile:
          state: directory
          suffix: .casks
        register: __homebrew_raw_casks

      - name: Download raw homebrew casks from Github
        get_url:
          url: "{{ item.url }}"
          dest: "{{ __homebrew_raw_casks.path }}/{{ item.name }}"
        loop: "{{ homebrew_raw_github_packages }}"

      - name: Append raw casks to homebrew_cask_apps
        set_fact:
          homebrew_cask_apps: "{{ homebrew_cask_apps + [lookup('ansible.builtin.fileglob', __homebrew_raw_casks.path ~ '/*')] }}"

      tags: ['homebrew']


  roles:
    - role: elliotweiser.osx-command-line-tools

    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']

    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ['dotfiles']

    - role: geerlingguy.mac.mas
      when: mas_installed_apps or mas_installed_app_ids
      tags: ['mas']

    - role: geerlingguy.mac.dock
      when: configure_dock
      tags: ['dock']

  tasks:
    - import_tasks: tasks/terminal.yml
      when: configure_terminal
      tags: ['terminal']

    - import_tasks: tasks/osx.yml
      when: configure_osx
      tags: ['osx']

    - import_tasks: tasks/vscode.yml
      when: configure_vscode
      tags: ['vscode']

    - block:
        - name: Run configured post-provision ansible task files.
          include_tasks: "{{ outer_item }}"
          loop_control:
            loop_var: outer_item
          with_fileglob: "{{ post_provision_tasks|default(omit) }}"
      tags: ['post']
