# Configure ZSH

- name: Check if oh-my-zsh is already present
  stat:
    path: ~/.oh-my-zsh
  register: __omzsh_installed

- name: Install oh-my-zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  when: not __omzsh_installed.stat.exists

- name: Install power10k theme
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: ~/.oh-my-zsh/custom/themes/powerlevel10k
    depth: 1
